---
title: "Reviewer Response"
output: html_document
---

# AE

::: callout
## Overall Evaluation
Overall largely
This paper provides an interesting overview of graphics used to portray data on the COVID 19 pandemic, largely from popular media. It attempts to use ideas and principles of graphics design and human factors
studies of graphical perception to evaluate the effectiveness of these displays for the public and policy
makers.

All in all, I think it largely succeeds in these aims and would be a suitable and interesting article for JDSSV readers. However, the two reviewers make substantial suggestions and comments which need to be considered before it is ready for publication. I recommend acceptance, following suitable revision (together with a reply from the authors to these reviews).
:::


Specific reviewer comments are addressed below, here, we address additional discussions brought up by the AE in response to the reviewers' comments.

::: callout
## Reviewer 2 - Principles

To the reviewer’s comment, I add that there needs to some clear statement regarding the match
between the design of a graphic and the capabilities of the intended audience in determining whether a
graphic display is successful for its intended purpose. This is more important than simple design rules.
:::

We have added a short paragraph addressing this in the data communication subsection of the introduction, and used the opportunity to state that we have primarily focused on charts intended for mass consumption rather than experts in public health or epidemiology.

::: callout
## Other comments: Proportional symbol maps

I was very surprised to see no mention or illustration of anamorphic maps or cartograms, where the area of each geographical unit is transformed to represent the count (cases/deaths). I strongly suggest including something on this.
:::

We have added a cartogram to the discussion of proportional symbol maps and choropleths. Thank you for catching an obvious omission on our part.

::: callout
### Other comments: Color scheme obstructions

Color scheme is mentioned only in regard to Fig 6, but there are other examples where the color scheme used could be noted, either positively or negatively.

:::

We have added additional analysis of color where we feel it is useful; Figure 12 is one case where we chose not to mention color in part because I (Susan) can't tell if it's effective or not - I'm colorblind, and while I have trouble with streamgraphs in general, that is particularly true if color is actually meaningful. 

::: callout
### Other comments: Uncertainty

Uncertainty: In the list of aspects mentioned in the middle of P 2, I am struck by the absence of mention
of uncertainty in visual representations of COVID. Clearly, the data are complex as they are, but
understanding their uncertainty is also a topic that could be mentioned or discussed.

:::

We wholeheartedly agree - uncertainty should be mentioned in the introduction, though I can't think of any specific examples of addressing the uncertainty through visualization (as opposed to footnotes about data quality) in mainstream graphics which were circulated at the time. Still, that is a rather glaring omission from both our discussion and the collection of graphs we've accumulated as interesting.

::: callout
### Other comments: Temporal narrative

In Section 3, The temporal narrative, there could usefully be some discussion, and perhaps an illustration
of the use of dynamic charts like the moving bubble chart, to liberate the X axis from time, using
animation or an interactive slider.

:::

We've added a moving bubble chart - again, this is an obvious omission. Thank you for bringing it to our attention. Interestingly, it was somewhat difficult to find a chart like this in a mainstream media outlet when searching through retrospectively. Part of that may be the fact that the web isn't great at keeping archival content, and many of these dashboards have been overwritten through successive modification. I suspect another part, however, is that moving bubble charts require a lot of effort to read and understand, and possibly were more common on social media and in the data vis community writ large than in media intended for the general public.

::: callout
### Other comments: standardization

More prominence could be given to the thoughtful standardization that went into some of these
displays to provide comparability of representation across global and local geographies and over
multiple waves of the pandemic. For example, in the early days cases and deaths were tied to calendar
dates giving time series charts with different origins. The simple device (I believe from Burn-Murdoch of
the FT) of making these all start when N cases had been observed was a game changer. There are
probably other examples.

:::

There may be other examples, but this is a good one. We've added a comment to that effect in the discussion of time series data, but we also mention standardization w.r.t. area and population in the choropleth/cartogram section. While the topic probably deserves a more thorough treatment, it's not easy to slide it in and maintain the current structure of the paper, so we hope that this suffices.



## Reviewer 1

::: callout
### How was the sample of publications selected? Under what criteria?    

As it stands, the selection seems arbitrary and very limited. Why the Financial Times and The New York Times and not others? Why not analyzing visualizations from non-Western countries? If the authors want to talk about a “global narrative”, the selection of graphics should also be global. A comparative cross-cultural study would be pretty productive, as it might reveal similarities and differences of graphics from different regions.
:::

The authors are from the United States and Germany; while we participated in many discussions on global social media platforms such as Twitter, we do not have the global perspective (or even facility with sufficient languages) to undertake a review of a global sample of media relating to COVID. We have added a section which explicitly states how charts were selected and what our individual biases are with respect to geography and culture. 


::: callout
### Principles

The authors say that Edward Tufte’s optimization of data-to-ink ratio is a “general principle of visualization”. That’s quite an overstatement. Tufte’s data-to-ink ratio is more of a very subjective, highly flexible guideline that is extremely dependent on factors such as the type of audience, culture, publication, etc.

To begin with, empirical evidence doesn’t support at all that highly stripped-down, high data-to-ink graphics support understanding in any way. As long as the non-data ink in a visualization doesn’t grossly obscure the representation of the data itself, it’s harmless. Moreover, it can even be beneficial, as it might help attract a reader’s attention to the information —in some studies, readers expressed their dislike for the highly sanitized, modernist/minimalist visual style Tufte is an advocate for.

I’d eliminate the reference to this non-principle and I’d stick to the other principle, which is truly advisable and normative; from the paper itself: “ensuring clear understanding by organising the graphics in such a way that the story of the data is told most effectively.”

This would need to be extended, though, and more clearly explained. Making a visualization understandable doesn’t depend just on organization. It also involves making choices about encodings, types of charts and maps and, more importantly (something that I think this paper overlooks) actually testing that the graphic actually conveys the intended information to the audience it’s supposed to inform. Anyone who works in visualization will tell you that simply applying “good design practices” to a visualization will never guarantee for certain that it is understood.

:::

We have modified the principles section to remove the reference to Tufte and the data/ink ratio. We have slightly reorganized the introduction section to add subsections, and have added an additional paragraph which discusses the series of choices made in the process of designing a data visualization. While the general guidelines for making these choices are somewhat outside the scope of this paper, as this is an article, and not a book, and proper treatment of these decisions in a broader context would require at least a book, we hope that highlighting the more general context surrounding the creation of data visualizations and explicitly defining the scope for this article provides some additional clarity.


::: callout
### Graphics Commentary

I believe that the commentary on the graphics the authors chose would need to be more extensive and detailed. Just to give an example, they compare choropleth maps to proportional symbol maps, but they don’t reflect on the many shortcomings of the latter, such as the usual overlap between the scaled symbols. This might be related to space limits in the journal, but I think that this is a paper that deserves to be at least double its length to be truly comprehensive and detailed enough.

The authors also make too many assumptions about how a graphic will be interpreted. This is a direct quote: “The advantage of these displays is that they are very simple and allow for viewers to gain an intuitive understanding of the data”. Where is the evidence for such an assertion? The fact that the authors —likely professionals who are very familiar with statistics and visualization— find a graphic intuitive doesn’t make that graphic intuitive to other audiences. (The authors themselves actually address this in the following section, about log scales, arguably the best one in the paper.)

:::

While the editor has cautioned us not to double the length of the paper, where possible we have attempted to address some obvious shortcomings in our initial discussion without unduly increasing the paper's length. This paper is in part a result of discussing COVID graphics in several groups and seminars with data visualization professionals and also with laypeople; as a result, while we cannot directly cite a source saying that a specific graphic is simple and intuitive, we can directly assess the visual complexity of the chart and we can distill down the series of discussions we've had about these topics over the course of the pandemic to arrive at what we hope are fairly useful conclusions. In an attempt to be a bit more precise, however, where we could find relevant discussions on social media, we have included citations of those discussions to provide some support for claims that we have made summarizing the views of others.


## Reviewer 2

::: callout
### Phrasing

This is clearly an article by researchers for whom English is likely a second language. While fluent, the wording is often obtuse and clunky. I have made a number of changes in the text to show where it might be improved.
:::

We appreciate the edits. We have addressed many of the stylistic suggestions where appropriate. In other cases, we have modified the paper in ways that rendered the suggested edits moot, and we hope the reviewer will appreciate the final result in any case.

::: callout
### Organization

More importantly, there is a mass of data here and a failure of organization. The whole requires a rewrite that distinguishes with one example for each the use of chloropleth, dot maps, tables, annimations, etc. In the chloropleth section and dot map one can distiguish between raw numbers and those that are, for example, cases/per 1000 persons. The use of sliders and annimation would be a separate section.

The goal is simple. A better abstract would say:  Maps and graphs have been extensively used in presenting the evolving state of the Covid-19 pandemic globally, nationally, and locally. This article seeks to review the types of maps and graphs employed by major news media and to assess the degree to which they served as communicative arguments useful both as a basis of public understanding of the pandemic and, at different stages, the rationale behind policies implimented to reduce its impact.

As is, it reads badly and the organization is such that its points get lost. Keep the illustrations to the points you wish to make. Distinguish betwen map types and their uses. Use A, B-heads as you reorder your argument. 

And in the discussion ... what have we learned? Well, there are static and dynamic maps, the former most common in news presentations, the latter in web-based. A trivial but useful point. Sliders are a good example how the latter expands what is in the traditional news map. 

:::

The organization of this paper is certainly not the same as that which is proposed, in part because we have taken a narrative view that explores the different communication narratives of visualizations during the pandemic. Because we focus on the narratives and look at the chart types employed in service of those narratives, organization necessarily deviates from a straightforward analysis of each chart type in sequence, but this is by design.
